name: Type Check

on:
  push:
    branches: [main, feature/**, dependabot/**]
  pull_request:
    branches: [main, feature/**, dependabot/**]

jobs:
  type-check:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9", "3.10"]

    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --sync

      - name: Test with pytest
        run: poetry run poe type-check
